(packages (cons*   nss-certs
                   xorg-server
                   xprop
                   xclip
                   xbitmaps
                   xrandr
                   xsensors
                   xinit
                   xinput
                   xcursor-themes
                   xdg-user-dirs
                   xdotools
                   ncurses
                   netcat
                   nginx
                   nmap
                   network-manager
                   ecl
                   ecl-alexandria
                   ecl-cl-ppcre
                   ecl-clx
                   mpd
                   ncmpc
                   zathura
                   zathura-cb
                   zathura-djvu
                   zathura-pdf-mupdf
                   zathura-ps
                   dmenu   
                   emacs
                   emacs-guix
                   emacs-xelb
                   emacs-exwm
                   qutebrowser
                   emacs-dashboard
                   emacs-ace-window
                   emacs-add-hooks
                   emacs-auctex
                   emacs-evil
                   emacs-evil-collection
                   emacs-evil-smartparens
                   emacs-evil-surround
                   emacs-org
                   emacs-org-bullets
                   emacs-org-contrib
                   emacs-better-defaults
                   emacs-bash-completion
                   emacs-emms-player-mpv
                   emacs-emms-mode-line-cycle
                   emacs-ergoemacs-mode
                   emacs-god-mode
                   emacs-helm
                   emacs-hydra
                   emacs-inf-ruby
                   emacs-key-chord
                   emacs-multiple-cursors
                   emacs-neotree
                   emacs-smex
                   emacs-use-package
                   emacs-w3m
                   emacs-which-key
                   emacs-pass
                   emacs-robe
                   emacs-smart-mode-line
                   emacs-smartparens
                   emacs-exec-path-from-shell
                   emacs-eimp
                   emacs-el2org
                   emacs-elfeed
                   emacs-biblio
                   emacs-darkroom
                   emacs-dired-hacks
                   emacs-download-region
                   emacs-easy-kill
                   %base-packages))
